[package]
name = "kubeclient"
version = "0.1.0"
authors = ["Andor Uhlár <andor44@gmail.com>"]

[dependencies]
# http requests
reqwest = "0.7"

# serialization
serde = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
serde_derive = "1.0"

# converting PEM certs to DER
pem-parser = "0.1.1"
